categories:
  - Imaging
description: Intensity-based Image Registration
long_description: |
  This tool estimates the (affine) transformation matrix for registration of two images based on intensity information.
name: image_registration_affine
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/image_registration_affine/
