categories:
  - Imaging
description: Crop image
long_description: Crops an image using one or more regions of interest.
name: crop_image 
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/crop_image/
