categories:
  - Imaging
description: Globally optimal segmentation method based on superadditivity and deformable shape models for cell nuclei in fluorescence microscopy images
long_description: Globally optimal segmentation method based on superadditivity and deformable shape models for cell nuclei in 2-D fluorescence microscopy images.
name: superdsm
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/superdsm/
