
categories:
  - Imaging
description: Binary Image to Points
long_description: This tool calculates the center of mass of a binary image.
name: binaryimage2points
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/binaryimage2points/
