categories:
  - Imaging
description: Detection Visualization
long_description: This tool visualizes detection.
name: detection_viz
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/detection_viz/
