categories:
  - Imaging
description: Concatenate images
long_description: This tool concatenates images.
name: concat_channels
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/concat_channels/
