categories:
  - Imaging
description: Extracts image metadata
long_description: This tool extracts metadata from an image.
name: image_info 
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/image_info/
