categories:
  - Imaging
description: Image feature extraction
long_description: Extraction of various features in 2-D or 3-D images.
name: 2d_feature_extraction 
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/2d_feature_extraction/
