categories:
  - Imaging
description: 2D feature extraction
long_description: Extraction of various features in 2D.
name: 2d_feature_extraction
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/2d_feature_extraction/
