categories:
  - Imaging
description: Colocalization Visualization
long_description: This tool is deprecated.
name: colocalization_viz
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/colocalization_viz/
