categories:
  - Imaging
description: Scale image
long_description: Scales image by a certain factor using nearest, bilinear or bicubic interpolation.
name: scale_image
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/scale_image/
