categories:
  - Imaging
description: Anisotropic image diffusion
long_description: Edge-preserving, Anisotropic image diffusion.
name: anisotropic_diffusion
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/anisotropic-diffusion/
