name: spot_detection_2d
owner: imgteam
categories:
  - Imaging
description: Spot detection in 2D image sequence
long_description: |
  This tool detects spots and measures the intensities in a 2D image sequence based on local intensity maxima.
homepage_url: https://github.com/BMCV/galaxy-image-analysis
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/spot_detection_2d/