categories:
  - Imaging
description: 2d auto local threshold
long_description: This tool is deprecated.
name: 2d_local_threshold
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/2d_auto_local_threshold/
