categories:
  - Imaging
description: Compute Voronoi tesselation
long_description: Compute Voronoi tesselation for labeled images.
name: voronoi_tesselation 
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/voronoi_tesselation