name: curve_fitting
owner: imgteam
categories:
  - Imaging
description: Polynomial curve fitting to data points
long_description: |
  This tool fits (1st- or 2nd-degree) polynomial curves to data points.
homepage_url: https://github.com/BMCV/galaxy-image-analysis
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tree/master/tools/curve_fitting/