categories:
  - Imaging
description: Color-deconvolution methods
long_description: This tools does color space transformation using preset transformation matrices or color space decomposition.
name: color_deconvolution
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/color-deconvolution/
