name: highdicom

owner: imgteam

description: Suite of tools for processing DICOM datasets

long_description: |
  DICOM is a widely established file format in medical imaging. A DICOM dataset contains rich metadata (patient, study
  info) and the actual medical image pixel or voxel data. The image data can be single-channel or multi-channel, and it
  can also be organized in multiple frames (e.g., spatial tiles of a mosaic, spatial slices, or time steps).

  This tool suite provides wrappers for the highdicom Python package and enables processing of DICOM datasets in Galaxy.

categories:
  - Imaging

homepage_url: https://github.com/ImagingDataCommons/highdicom
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/highdicom/

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"
