categories:
  - Imaging
description: Landmark Registration using Least Squares
long_description: |
  This tool estimates the (affine) transformation matrix using least squares given two sets of 2d coordinates of landmarks.
name: landmark_registration_ls
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/landmark_registration_ls/
