categories:
  - Imaging
description: Landmark Registration using Least Squares
long_description: |
  This tool is deprecated.
name: landmark_registration_ls
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/landmark_registration_ls/
