categories:
  - Imaging
description: Overly moving and fixed image
long_description: This tool generates an overlay of two images of which one was transformed to match the other.
name: overlay_moving_and_fixed_image
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/overlay_moving_and_fixed_image/
