categories:
  - Imaging
description: Overlay moving and fixed image
long_description: This tool is deprecated.
name: overlay_moving_and_fixed_image
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/overlay_moving_and_fixed_image/
