categories:
  - Imaging
description: Landmark Registration
long_description: |
  1) Estimation of the affine transformation matrix between two sets of 2d points; 2) Piecewise affine transformation of points based on landmark pairs.
name: landmark_registration
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/landmark_registration/
