categories:
  - Imaging
description: Compute image features using mahotas.
long_description: Mahotas is a computer vision and image processing library for Python. This tool computes image features using mahotas.
name: mahotas_features
owner: imgteam
homepage_url: https://github.com/luispedro/mahotas
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/mahotas-features/
