categories:
  - Imaging
description: Compute features using mahotas.
long_description: Compute features using mahotas.
name: mahotas_features
owner: imgteam
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/mahotas-features/
