categories:
  - Imaging
description: Coordinates of ROI
long_description: Obtains the coordinates regions of interest on an image
name: coordinates_of_roi
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/coordinates_of_roi/
