categories:
  - Imaging
description: split object by watershed
long_description: Split binary image by using distance transform and watershed
name: 2d_split_binaryimage_by_watershed
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/2d_split_binaryimage_by_watershed/
