categories:
  - Imaging
description: Projective transformation - Points
long_description: This tool performs a projective transformation of input coordinates with a warp matrix.
name: projective_transformation_points
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/projective_transformation_points/
