categories:
  - Imaging
description: Ray testing
long_description: Ray testing
name: ray
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/ray/
