categories:
  - Convert Formats
description: Unzip file
long_description: Unzip file to collection
name: unzip
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/unzip/
