categories:
  - Imaging
description: Ridge filter for images
long_description: Apply a ridge filter to an image
name: ridge_filter
owner: imgteam
homepage_url: https://scikit-image.org/docs/0.25.x/auto_examples/edges/plot_ridge_filter.html
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/ridge_filter/
