categories:
  - Imaging
description: Split image along axes
long_description: This tool splits an image along a specific axis (e.g., channels).
name: split_image
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/split_image/
