categories:
  - Imaging
description: Image enhancement filter
long_description: Apply image enhancement filter
name: 2d_simple_filter    
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/enhancement_filter/
