owner: imgteam

suite:
  name: suite_cv2

  description: Suite of tools for wrapping the cv2 python module

  long_description: |
    OpenCV is a library of programming functions mainly for real-time computer vision. OpenCV is the world's biggest and open source vision library
    with more the 2500 algorithms for tasks such as object detection, facial recognition, and image stitching, 
    The Python interface cv2 allows accessing the functionalities provided by the OpenCV library.

    This tool suite provides wrappers for the cv2 Python package enabling processing of image and video in Galaxy using OpenCV.
 

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"

long_description: |
  Enables processing image and video in Galaxy using OpenCV. Based on the cv2 Python package.

type: unrestricted

categories:
  - Imaging

homepage_url: https://github.com/opencv/opencv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/cv2