categories:
  - Imaging
description: Overlay segmentation mask
long_description: This tool is deprecated.
name: overlay_segmentation_mask
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/overlay_segmentation_mask/
