categories:
  - Imaging
description: Points to label image
long_description: Converts points to label image
name: points2labelimage
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/points2labelimage/
