categories:
  - Imaging
description: Points 2 Label Image
long_description: This tool converts points to a label image.
name: points2labelimage
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/\points2labelimage
