categories:
  - Imaging
description: Slice image
long_description: Slices original image into several smaller patches
name: slice_image
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/slice_image/
