categories:
  - Imaging
description: 2d automatic threshold
long_description: Automatic thresholding in 2D
name: 2d_auto_threshold
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/2d_auto_threshold/
