categories:
  - Imaging
description: Automatic thresholding
long_description: Applying a standard thresholding method to an image.
name: 2d_auto_threshold 
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/2d_auto_threshold/
