categories:
  - Imaging
description: Process images using mathematical expressions
long_description: Process images using mathematical expressions.
name: image_math 
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/image_math