name: points_association_nn
owner: imgteam
categories:
  - Imaging
description: Association of points in consecutive frames
long_description: |
  This tool associates points in consecutive frames (slices) using the nearest neighbor algorithm.
homepage_url: https://github.com/BMCV/galaxy-image-analysis
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/points_association_nn/