categories:
  - Imaging
description: Count Objects
long_description: Count objects in an image
name: count_objects
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/count_objects/
