categories:
  - Imaging
description: Label Image to Points
long_description: This tool converts a label image to points.
name: labelimage2points
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/\labelimage2points
