categories:
  - Imaging
description: Convert single-channel to multi-channel image
long_description: This tools converts a single-channel image to a multi-channel image by repeating the channel multiple times.
name: repeat_channels
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/repeat_channels/
