categories:
  - Imaging
description: Colorize label map
long_description: Colorize label map for visualization.
name: colorize_labels 
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/colorize_labels