categories:
  - Imaging
description: WSI Extract Top View
long_description: Extracts the top view of a whole-slide image (=virtual slide).
name: wsi_extract_top_view
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/wsi_extract_top_view/
