categories:
  - Imaging
description: Merge Neighbours in Label Image
long_description: This tools merges nearby objects in a label image using the minimum pixel distance.
name: mergeneighboursinlabelimage
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/\mergeneighboursinlabelimage
