categories:
  - Imaging
description: Points to Binary Image
long_description: Converts points to binary image.
name: points2binaryimage
owner: thomaswollmann
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tools/points2binaryimage/
