name: normalize_intensities
owner: imgteam
categories:
  - Imaging
description: Normalize intensities of an image
long_description: |
  This tool normalizes the intensities of an image to zero mean and unit variance.
homepage_url: https://github.com/BMCV/galaxy-image-analysis
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/normalize_intensities/